export const content = {
  en: {
    brandMain: "Dhruv Vihaan",
    brandSub: "Tour & Travels",
    brandSubScript: "ध्रुव विहान टूर एंड ट्रेवल्स",
    toggleBtn: "हिंदी में देखें 🇮🇳",
    callStrip: "📞 Call Now — Dheeraj Pal:",
    callStrip2: "| 💬 Chat on WhatsApp",
    navLinks: ["Home", "Destinations", "Packages", "Gallery", "Contact"],
    navIds: ["home", "destinations", "packages", "gallery", "contact"],
    navCta: "📞 Book Now",
    heroBadge: "✦ Sacred Journey Awaits ✦",
    heroTitle1: "Dhruv Vihaan",
    heroTitle2: "Tour & Travels",
    heroSubtitle: "Discover the Divine Heart of Madhya Pradesh",
    heroDesc: "Embark on a soulful journey through Ujjain, Omkareshwar & Indore. Experience ancient temples, sacred rivers, and the timeless spirituality of Central India.",
    heroBtnPrimary: "Book Your Journey ✦",
    heroBtnOutline: "Explore Destinations",
    stats: [["500+","Happy Travelers"],["3","Holy Destinations"],["10+","Packages"],["24/7","Support"]],
    destTag: "✦ Holy Destinations ✦",
    destTitle: "Sacred Places of",
    destTitleGold: "Madhya Pradesh",
    destDesc: "Journey to the most revered spiritual destinations in the heart of India",
    destinations: [
      {
        emoji: "🕌", label: "Ujjain", title: "Ujjain – City of the Great God",
        tag: "Jyotirlinga",
        desc: "One of the seven sacred cities of India, home to the revered Mahakaleshwar Jyotirlinga. Experience the mystical Bhasma Aarti at dawn.",
        bg: "linear-gradient(135deg,#FF6B00,#8B2500)",
        highlights: ["Mahakaleshwar","Kumbh Mela","Kal Bhairav","Shipra Ghat"],
      },
      {
        emoji: "🛕", label: "Omkareshwar", title: "Omkareshwar – Island of Om",
        tag: "Jyotirlinga",
        desc: "Situated on an island shaped like the sacred 'Om', this divine destination houses the Omkareshwar and Mamleshwar Jyotirlingas.",
        bg: "linear-gradient(135deg,#6B0F1A,#FF6B00)",
        highlights: ["Omkareshwar Temple","Narmada Aarti","Boat Ride","Siddhanath"],
      },
      {
        emoji: "🌆", label: "Indore", title: "Indore – The Cultural Capital",
        tag: "Cultural Hub",
        desc: "India's cleanest city and cultural heart of Madhya Pradesh. Explore the vibrant Rajwada, Sarafa Bazaar, and mouth-watering street food.",
        bg: "linear-gradient(135deg,#1A0A00,#8B6914)",
        highlights: ["Rajwada Palace","Sarafa Bazaar","Lal Baag","Chappan Dukaan"],
      },
    ],
    khajranaTag: "✦ Top 10 Must-Visit ✦",
    khajranaTitle: "Khajrana",
    khajranaTitleGold: "Ganesh Mandir",
    khajranaDesc: "The miraculous Ganesh temple of Indore — explore every sacred spot",
    places: [
      { num:"01", icon:"🙏", name:"Khajrana Ganesh Mandir", desc:"The most revered Ganesh temple in Indore, known for miraculous wish-fulfillment. Millions visit annually." },
      { num:"02", icon:"🌸", name:"Prasad Counter & Modak Stall", desc:"Taste the sacred Modak and Ladoo prasad made fresh daily at the temple complex." },
      { num:"03", icon:"🪔", name:"Morning Aarti (5:00 AM)", desc:"Witness the breathtaking Mangal Aarti as priests perform rituals to welcome the deity at dawn." },
      { num:"04", icon:"💧", name:"Holy Kund (Sacred Pond)", desc:"A serene holy pond near the temple where devotees take a sacred dip on auspicious occasions." },
      { num:"05", icon:"🎪", name:"Ganesh Van (Temple Garden)", desc:"A lush garden surrounding the temple complex — perfect for peaceful strolls and meditation." },
      { num:"06", icon:"🛍️", name:"Religious Market (Bazaar)", desc:"Explore vibrant stalls selling religious items, flowers, jewelry, and traditional MP artifacts." },
      { num:"07", icon:"🍛", name:"Local Prasad Thalis", desc:"Savor traditional bhojan thalis served near the temple — authentic Malwi cuisine at its finest." },
      { num:"08", icon:"🎵", name:"Evening Aarti (Sandhya)", desc:"The mesmerizing evening aarti with dhol, shehnai, and hundreds of diyas lighting the temple." },
      { num:"09", icon:"🏮", name:"Diwali & Festival Celebrations", desc:"During Ganesh Chaturthi and Diwali, the temple transforms into a breathtaking festival of lights." },
      { num:"10", icon:"🌟", name:"Wish Fulfillment Ritual", desc:"Devotees tie threads and offer coconuts as part of the sacred mannat ritual at the temple." },
    ],
    whyTag: "✦ Why Choose Us ✦",
    whyTitle: "Travel with",
    whyTitleGold: "Confidence",
    why: [
      {icon:"🚗", title:"Comfortable Transport", desc:"AC cabs and buses for all group sizes — clean, punctual, and safe."},
      {icon:"🏨", title:"Premium Hotels", desc:"Carefully selected accommodations near temple zones with modern amenities."},
      {icon:"🎯", title:"Expert Local Guides", desc:"Knowledgeable guides who bring history and spirituality alive at every site."},
      {icon:"💰", title:"Best Price Guarantee", desc:"Transparent pricing with no hidden charges. Best rates in Madhya Pradesh."},
      {icon:"📞", title:"24/7 Support", desc:"Dheeraj ji is always available for your assistance — before, during, and after."},
      {icon:"🙏", title:"Spiritual Experience", desc:"Curated temple visits with priority darshan arrangements at key shrines."},
    ],
    pkgTag: "✦ Tour Packages ✦",
    pkgTitle: "Choose Your",
    pkgTitleGold: "Sacred Journey",
    pkgBookBtn: "Book This Package",
    packages: [
      {
        icon:"🌅", title:"Ujjain Day Tour", price:"Starting ₹1,499/person",
        features:["Mahakaleshwar Darshan","Bhasma Aarti Priority","Kal Bhairav Temple","Shipra River Aarti","Hotel Stay Included","Guided Tour"],
      },
      {
        icon:"🕉️", title:"Divine Trio Package", price:"Starting ₹4,999/person", featured:true, badge:"MOST POPULAR",
        features:["Ujjain + Omkareshwar + Indore","3 Days 2 Nights","AC Transport","Premium Hotels","Both Jyotirlinga Darshan","All Meals Included","Expert Guide"],
      },
      {
        icon:"🛕", title:"Omkareshwar Special", price:"Starting ₹1,999/person",
        features:["Omkareshwar Jyotirlinga","Narmada Boat Ride","Mamleshwar Temple","Sunrise Aarti","Hotel Stay","Cab Included"],
      },
    ],
    galleryTag: "✦ Gallery ✦",
    galleryTitle: "Moments of",
    galleryTitleGold: "Divine Beauty",
    gallery: [
      {emoji:"🕌", bg:"linear-gradient(135deg,#FF6B00,#6B0F1A)", caption:"Mahakaleshwar Temple, Ujjain"},
      {emoji:"🛕", bg:"linear-gradient(135deg,#8B2500,#3D0408)", caption:"Omkareshwar Jyotirlinga"},
      {emoji:"🌊", bg:"linear-gradient(135deg,#0A3D62,#1E6091)", caption:"Narmada River Aarti"},
      {emoji:"🏛️", bg:"linear-gradient(135deg,#6B0F1A,#8B6914)", caption:"Rajwada Palace, Indore"},
      {emoji:"🙏", bg:"linear-gradient(135deg,#D4A017,#8B2500)", caption:"Khajrana Ganesh Mandir"},
      {emoji:"🎪", bg:"linear-gradient(135deg,#1A0A00,#FF6B00)", caption:"Kumbh Mela, Ujjain"},
    ],
    testiTag: "✦ Testimonials ✦",
    testiTitle: "What Our",
    testiTitleGold: "Travelers Say",
    testimonials: [
      {stars:5, text:"Dheeraj bhai made our Ujjain trip absolutely divine! The Bhasma Aarti experience was once in a lifetime. Highly recommend Dhruv Vihaan Tour Travelers!", name:"Rajesh Sharma", city:"Bhopal", avatar:"👨"},
      {stars:5, text:"Superb service! The Omkareshwar package was perfectly planned. Everything from transport to hotel was excellent. Will book again!", name:"Priya Patel", city:"Mumbai", avatar:"👩"},
      {stars:5, text:"Best tour operator in Indore! Covered all three destinations beautifully. The guide was very knowledgeable. 10/10 experience!", name:"Sunil Verma", city:"Delhi", avatar:"🧔"},
    ],
    contactTag: "✦ Get In Touch ✦",
    contactTitle: "Book Your",
    contactTitleGold: "Sacred Journey Today",
    contactDesc: "Ready to experience the divine? Contact Dheeraj Pal for customized tour packages across Ujjain, Omkareshwar, Indore & beyond.",
    contactItems: [
      {icon:"📞", label:"Mobile / WhatsApp", value:"6265370030"},
      {icon:"👤", label:"Tour Coordinator", value:"Dheeraj Pal"},
      {icon:"🏢", label:"Company", value:"Dhruv Vihaan Tour & Travels"},
      {icon:"📍", label:"Base Location", value:"Indore, Madhya Pradesh"},
      {icon:"🕐", label:"Working Hours", value:"6:00 AM – 10:00 PM (Daily)"},
      {icon:"✈️", label:"Service Area", value:"Ujjain • Omkareshwar • Indore"},
    ],
    formTitle: "🙏 Request a Booking",
    formName: "Your Name", formNamePh: "Full Name",
    formPhone: "Phone Number", formPhonePh: "Mobile Number",
    formDest: "Select Destination", formDestPh: "Choose Destination...",
    formDestOpts: ["Ujjain Day Tour","Omkareshwar Special","Divine Trio (Ujjain + Omkareshwar + Indore)","Khajrana Ganesh Mandir Tour","Custom Package"],
    formDate: "Travel Date",
    formMsg: "Your Message", formMsgPh: "Group size, special requirements...",
    formSubmit: "📲 Send via WhatsApp",
    formSubmitted: "✓ Sent to WhatsApp!",
    formOr: "Or call directly:",
    footerLinks: ["Ujjain","Omkareshwar","Indore","Khajrana","Packages"],
    footerContact: "Contact: Dheeraj Pal",
    footerCopy: "© 2024 Dhruv Vihaan Tour & Travels • Dheeraj Pal • Indore, MP • All Rights Reserved",
    footerCopy2: "🙏 Crafted with love for Divine Travelers",
    whatsappMsg: (d) => `Hello Dheeraj ji! My name is ${d.name} (Ph: ${d.phone}). I am interested in ${d.destination || "your tour packages"}. Travel Date: ${d.date || "TBD"}. ${d.message}`,
  },
  hi: {
    brandMain: "ध्रुव विहान",
    brandSub: "टूर एंड ट्रेवल्स",
    brandSubScript: "Dhruv Vihaan Tour & Travels",
    toggleBtn: "English में देखें 🇬🇧",
    callStrip: "📞 अभी कॉल करें — धीरज पाल:",
    callStrip2: "| 💬 WhatsApp पर बात करें",
    navLinks: ["होम","गंतव्य","पैकेज","गैलरी","संपर्क"],
    navIds: ["home","destinations","packages","gallery","contact"],
    navCta: "📞 अभी बुक करें",
    heroBadge: "✦ दिव्य यात्रा आपकी प्रतीक्षा कर रही है ✦",
    heroTitle1: "ध्रुव विहान",
    heroTitle2: "टूर एंड ट्रेवल्स",
    heroSubtitle: "मध्यप्रदेश के पवित्र हृदय की खोज करें",
    heroDesc: "उज्जैन, ओंकारेश्वर और इंदौर की आत्मीय यात्रा पर चलें। प्राचीन मंदिरों, पावन नदियों और मध्य भारत की शाश्वत आध्यात्मिकता का अनुभव करें।",
    heroBtnPrimary: "यात्रा बुक करें ✦",
    heroBtnOutline: "गंतव्य देखें",
    stats: [["५००+","खुश यात्री"],["३","पवित्र स्थान"],["१०+","पैकेज"],["२४/७","सहायता"]],
    destTag: "✦ पवित्र गंतव्य ✦",
    destTitle: "मध्यप्रदेश के",
    destTitleGold: "धार्मिक स्थल",
    destDesc: "भारत के हृदय में स्थित सबसे पूजनीय आध्यात्मिक स्थलों की यात्रा करें",
    destinations: [
      {
        emoji:"🕌", label:"उज्जैन", title:"उज्जैन – महाकाल की नगरी",
        tag:"ज्योतिर्लिंग",
        desc:"भारत के सात पवित्र नगरों में से एक — महाकालेश्वर ज्योतिर्लिंग का धाम। भस्म आरती का दिव्य अनुभव लें जो आत्मा को पावन कर देती है।",
        bg:"linear-gradient(135deg,#FF6B00,#8B2500)",
        highlights:["महाकालेश्वर","कुंभ मेला","काल भैरव","शिप्रा घाट"],
      },
      {
        emoji:"🛕", label:"ओंकारेश्वर", title:"ओंकारेश्वर – ओम द्वीप",
        tag:"ज्योतिर्लिंग",
        desc:"पवित्र 'ॐ' के आकार के द्वीप पर स्थित यह स्थान ओंकारेश्वर और ममलेश्वर ज्योतिर्लिंगों का पवित्र धाम है।",
        bg:"linear-gradient(135deg,#6B0F1A,#FF6B00)",
        highlights:["ओंकारेश्वर मंदिर","नर्मदा आरती","नाव सवारी","सिद्धनाथ"],
      },
      {
        emoji:"🌆", label:"इंदौर", title:"इंदौर – स्वच्छ व सांस्कृतिक नगरी",
        tag:"सांस्कृतिक केंद्र",
        desc:"भारत का सबसे स्वच्छ शहर और मध्यप्रदेश का सांस्कृतिक हृदय। राजवाड़ा, सराफा बाजार और लजीज स्ट्रीट फूड का आनंद लें।",
        bg:"linear-gradient(135deg,#1A0A00,#8B6914)",
        highlights:["राजवाड़ा महल","सराफा बाजार","लाल बाग","छप्पन दुकान"],
      },
    ],
    khajranaTag: "✦ शीर्ष १० स्थान ✦",
    khajranaTitle: "खजराना",
    khajranaTitleGold: "गणेश मंदिर",
    khajranaDesc: "इंदौर का चमत्कारी गणेश मंदिर — हर पवित्र स्थान का अन्वेषण करें",
    places: [
      {num:"01",icon:"🙏",name:"खजराना गणेश मंदिर",desc:"इंदौर का सबसे पूजनीय गणेश मंदिर — मनोकामना पूर्ण करने वाला दिव्य स्थान। लाखों श्रद्धालु प्रतिवर्ष आते हैं।"},
      {num:"02",icon:"🌸",name:"प्रसाद काउंटर व मोदक स्टॉल",desc:"मंदिर परिसर में प्रतिदिन बनने वाले ताज़े मोदक और लड्डू का दिव्य प्रसाद ग्रहण करें।"},
      {num:"03",icon:"🪔",name:"प्रातः आरती (सुबह ५ बजे)",desc:"देवता के स्वागत में पुजारियों द्वारा की जाने वाली भव्य मंगल आरती का दर्शन करें।"},
      {num:"04",icon:"💧",name:"पवित्र कुण्ड",desc:"मंदिर के समीप स्थित पवित्र सरोवर जहाँ श्रद्धालु शुभ अवसरों पर स्नान करते हैं।"},
      {num:"05",icon:"🎪",name:"गणेश वन (मंदिर उद्यान)",desc:"मंदिर परिसर के चारों ओर हरा-भरा उद्यान — ध्यान और शांति के लिए आदर्श स्थान।"},
      {num:"06",icon:"🛍️",name:"धार्मिक बाजार",desc:"फूल, आभूषण, पूजन सामग्री और मध्यप्रदेश के पारंपरिक हस्तशिल्प की रंगीन दुकानें।"},
      {num:"07",icon:"🍛",name:"प्रसाद थाली",desc:"मंदिर के पास परोसी जाने वाली पारंपरिक भोजन थाली — असली मालवी स्वाद का अनुभव।"},
      {num:"08",icon:"🎵",name:"संध्या आरती (सायं)",desc:"ढोल, शहनाई और सैकड़ों दीपों के साथ होने वाली मनमोहक संध्या आरती।"},
      {num:"09",icon:"🏮",name:"दीवाली व उत्सव",desc:"गणेश चतुर्थी और दीवाली पर मंदिर रोशनी के अद्भुत महोत्सव में बदल जाता है।"},
      {num:"10",icon:"🌟",name:"मन्नत (इच्छापूर्ति विधि)",desc:"श्रद्धालु धागा बाँधते और नारियल चढ़ाते हैं — यह पवित्र मन्नत विधि विश्वभर में प्रसिद्ध है।"},
    ],
    whyTag: "✦ हमें क्यों चुनें ✦",
    whyTitle: "विश्वास के साथ",
    whyTitleGold: "यात्रा करें",
    why: [
      {icon:"🚗",title:"आरामदायक वाहन",desc:"सभी समूहों के लिए AC कैब और बसें — स्वच्छ, समय पर और सुरक्षित।"},
      {icon:"🏨",title:"प्रीमियम होटल",desc:"मंदिर क्षेत्र के पास सावधानी से चयनित आवास, आधुनिक सुविधाओं के साथ।"},
      {icon:"🎯",title:"स्थानीय विशेषज्ञ गाइड",desc:"ज्ञानी गाइड जो हर स्थान पर इतिहास और आध्यात्मिकता को जीवंत करते हैं।"},
      {icon:"💰",title:"सर्वोत्तम मूल्य गारंटी",desc:"पारदर्शी मूल्य, कोई छुपा शुल्क नहीं। मध्यप्रदेश में सर्वोत्तम दरें।"},
      {icon:"📞",title:"२४/७ सहायता",desc:"धीरज जी यात्रा से पहले, दौरान और बाद में हमेशा उपलब्ध हैं।"},
      {icon:"🙏",title:"आध्यात्मिक अनुभव",desc:"मुख्य मंदिरों में प्राथमिकता दर्शन की व्यवस्था के साथ दिव्य यात्रा।"},
    ],
    pkgTag: "✦ टूर पैकेज ✦",
    pkgTitle: "अपनी",
    pkgTitleGold: "पवित्र यात्रा चुनें",
    pkgBookBtn: "यह पैकेज बुक करें",
    packages: [
      {
        icon:"🌅", title:"उज्जैन दिवस यात्रा", price:"मात्र ₹१,४९९/व्यक्ति से",
        features:["महाकालेश्वर दर्शन","भस्म आरती प्राथमिकता","काल भैरव मंदिर","शिप्रा नदी आरती","होटल आवास सहित","गाइडेड टूर"],
      },
      {
        icon:"🕉️", title:"दिव्य त्रिवेणी पैकेज", price:"मात्र ₹४,९९९/व्यक्ति से", featured:true, badge:"सबसे लोकप्रिय",
        features:["उज्जैन + ओंकारेश्वर + इंदौर","३ दिन २ रात","AC वाहन सुविधा","प्रीमियम होटल","दोनों ज्योतिर्लिंग दर्शन","सभी भोजन सहित","विशेषज्ञ गाइड"],
      },
      {
        icon:"🛕", title:"ओंकारेश्वर स्पेशल", price:"मात्र ₹१,९९९/व्यक्ति से",
        features:["ओंकारेश्वर ज्योतिर्लिंग","नर्मदा नाव सवारी","ममलेश्वर मंदिर","सूर्योदय आरती","होटल आवास","कैब सेवा सहित"],
      },
    ],
    galleryTag: "✦ गैलरी ✦",
    galleryTitle: "दिव्य",
    galleryTitleGold: "सौंदर्य के क्षण",
    gallery: [
      {emoji:"🕌",bg:"linear-gradient(135deg,#FF6B00,#6B0F1A)",caption:"महाकालेश्वर मंदिर, उज्जैन"},
      {emoji:"🛕",bg:"linear-gradient(135deg,#8B2500,#3D0408)",caption:"ओंकारेश्वर ज्योतिर्लिंग"},
      {emoji:"🌊",bg:"linear-gradient(135deg,#0A3D62,#1E6091)",caption:"नर्मदा नदी आरती"},
      {emoji:"🏛️",bg:"linear-gradient(135deg,#6B0F1A,#8B6914)",caption:"राजवाड़ा महल, इंदौर"},
      {emoji:"🙏",bg:"linear-gradient(135deg,#D4A017,#8B2500)",caption:"खजराना गणेश मंदिर"},
      {emoji:"🎪",bg:"linear-gradient(135deg,#1A0A00,#FF6B00)",caption:"कुंभ मेला, उज्जैन"},
    ],
    testiTag: "✦ यात्री अनुभव ✦",
    testiTitle: "हमारे",
    testiTitleGold: "यात्री क्या कहते हैं",
    testimonials: [
      {stars:5,text:"ध्रुव विहान टूर ने हमारी उज्जैन यात्रा को अविस्मरणीय बना दिया! भस्म आरती का अनुभव जीवन में एक बार होता है। धीरज पाल जी को हार्दिक धन्यवाद!",name:"राजेश शर्मा",city:"भोपाल",avatar:"👨"},
      {stars:5,text:"बेहतरीन सेवा! ओंकारेश्वर पैकेज बिल्कुल परफेक्ट था। यातायात से होटल तक सब कुछ शानदार। दोबारा जरूर बुक करेंगे!",name:"प्रिया पटेल",city:"मुंबई",avatar:"👩"},
      {stars:5,text:"इंदौर का सबसे बढ़िया टूर ऑपरेटर! तीनों स्थानों को बखूबी कवर किया। गाइड बहुत ज्ञानी थे। १०/१० अनुभव!",name:"सुनील वर्मा",city:"दिल्ली",avatar:"🧔"},
    ],
    contactTag: "✦ संपर्क करें ✦",
    contactTitle: "आज ही अपनी",
    contactTitleGold: "पवित्र यात्रा बुक करें",
    contactDesc: "दिव्य अनुभव के लिए तैयार हैं? उज्जैन, ओंकारेश्वर, इंदौर व अन्य स्थानों के अनुकूलित टूर पैकेज के लिए धीरज पाल जी से संपर्क करें।",
    contactItems: [
      {icon:"📞",label:"मोबाइल / WhatsApp",value:"6265370030"},
      {icon:"👤",label:"टूर समन्वयक",value:"धीरज पाल"},
      {icon:"🏢",label:"संस्था",value:"ध्रुव विहान टूर एंड ट्रेवल्स"},
      {icon:"📍",label:"मुख्यालय",value:"इंदौर, मध्यप्रदेश"},
      {icon:"🕐",label:"कार्य समय",value:"प्रातः ६ बजे – रात्रि १० बजे (प्रतिदिन)"},
      {icon:"✈️",label:"सेवा क्षेत्र",value:"उज्जैन • ओंकारेश्वर • इंदौर"},
    ],
    formTitle: "🙏 बुकिंग अनुरोध भेजें",
    formName:"आपका नाम", formNamePh:"पूरा नाम",
    formPhone:"मोबाइल नंबर", formPhonePh:"मोबाइल नंबर",
    formDest:"गंतव्य चुनें", formDestPh:"गंतव्य चुनें...",
    formDestOpts:["उज्जैन दिवस यात्रा","ओंकारेश्वर स्पेशल","दिव्य त्रिवेणी (उज्जैन + ओंकारेश्वर + इंदौर)","खजराना गणेश मंदिर टूर","कस्टम पैकेज"],
    formDate:"यात्रा दिनांक",
    formMsg:"संदेश", formMsgPh:"समूह का आकार, विशेष आवश्यकताएं...",
    formSubmit:"📲 WhatsApp पर भेजें",
    formSubmitted:"✓ WhatsApp पर भेजा गया!",
    formOr:"या सीधे कॉल करें:",
    footerLinks:["उज्जैन","ओंकारेश्वर","इंदौर","खजराना","पैकेज"],
    footerContact:"संपर्क: धीरज पाल",
    footerCopy:"© २०२४ ध्रुव विहान टूर एंड ट्रेवल्स • धीरज पाल • इंदौर, मध्यप्रदेश • सर्वाधिकार सुरक्षित",
    footerCopy2:"🙏 दिव्य यात्रियों के लिए प्रेम से निर्मित",
    whatsappMsg: (d) => `नमस्ते धीरज जी! मेरा नाम ${d.name} है (मो: ${d.phone})। मुझे ${d.destination || "आपके टूर पैकेज"} में रुचि है। यात्रा दिनांक: ${d.date || "तय करना है"}। ${d.message}`,
  },
};